FROM pgvector/pgvector:0.8.0-pg15-bookworm

# install pg_cron
RUN apt-get update \
  && apt-get install -y postgresql-15-cron \
  && rm -rf /var/lib/apt/lists/*

# only preload pg_cron (not pgvector!)
RUN echo "shared_preload_libraries='pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample \
  && echo "cron.database_name='mydatabase'" >> /usr/share/postgresql/postgresql.conf.sample